{% set name = "covalent" %}
{% set version = "0.220.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/covalent-{{ version }}.tar.gz
  sha256: 5cb9763a11b248d8f925af07582ec2f358d17a9ec48bc603f310988f20bff0d2

build:
  entry_points:
    - covalent = covalent_dispatcher._cli.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - aiofiles >=0.8.0,<=22.1.0
    - aiohttp ==3.8.1
    - alembic >=1.8.0,<=1.8.1
    - click ==8.1.3
    - cloudpickle >=2.0.0,<=2.2.0
    - dask-core >=2022.6.0,<=2022.9.0
    - distributed
    - fastapi >=0.79.0,<=0.83.0
    - furl ==2.1.3
    - networkx ==2.8.6
    - psutil >=5.9.0,<=5.9.2
    - pydantic >=1.10.1,<=1.10.2
    - python-socketio ==5.7.1
    - requests >=2.24.0,<=2.28.1
    - simplejson ==3.17.6
    - sqlalchemy >=1.4.37,<=1.4.41
    - sqlalchemy-utils ==0.38.3
    - toml ==0.10.2
    - uvicorn >=0.18.2,<=0.18.3
    - watchdog ==2.2.1
    - werkzeug >=2.0.3,<=2.2.2

test:
  imports:
    - covalent
    - covalent_dispatcher
    - covalent_migrations
    - covalent_ui
  commands:
    - pip check
    - covalent --help
  requires:
    - pip

about:
  home: https://github.com/AgnostiqHQ/covalent
  summary: Covalent Workflow Tool
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
